services:
  crawl4ai:
    image: unclecode/crawl4ai:0.6.0-r1
    container_name: crawl4ai
    ports:
      - "11235:11235"
    networks:
      - scrapebun
    shm_size: "1g"
    restart: unless-stopped

  api:
    build:
      context: ./api
      dockerfile: Dockerfile
    container_name: api
    restart: unless-stopped
    ports:
      - "5000:5000"
    networks:
      - scrapebun
    depends_on:
      - crawl4ai

  ui:
    build:
      context: ./web
      dockerfile: Dockerfile
    container_name: ui
    restart: unless-stopped
    ports:
      - "3000:3000"
    networks:
      - scrapebun
    depends_on:
      - api
      
networks:
  scrapebun:
    external: true

